#!/usr/bin/perl

use strict;
use warnings;

use 5.010;
use QtCore4;
use QtGui4;
use MainWindow;

use File::Spec ();
# TODO activate next line if CPAN distribution
# use File::ShareDir;

use lib 'lib';
use Rogalik::Config;
#use Rogalik::DB; # not yet

sub init {
    # I don't know what can I do in init at the moment
}

sub main {
   my $app     = Qt::Application( \@ARGV );

   my $shareDir = File::Spec->catdir(
       Rogalik::Config::BASEDIR,
       'share',
   );
   # TODO use File::ShareDir::dist_dir if CPAN distribution

   my $splashImagePath = File::Spec->catdir(
       $shareDir,
       'splash/splash.png'
   );
#   say $splashImagePath;

   my $splashPixmap = Qt::Pixmap( $splashImagePath );

   my $splash = Qt::SplashScreen( $splashPixmap );
   $splash->show();
   $splash->showMessage( '' );

   init();

   sleep 2;

   my $mainWindow = MainWindow();
   $mainWindow->show();

   $splash->finish( $mainWindow );

   exit $app->exec();
}

main();
