#!/usr/bin/perl

use strict;
use warnings;

use 5.010;
use Data::Dumper;

use lib 'lib';
use Rogalik::Config;
use Rogalik::DB;

use QtCore4;
use QtGui4;
use MainWindow;

use File::Spec ();
# TODO activate next line if CPAN distribution
# use File::ShareDir;

sub init {
    # 1. Check if alive characters exists
    my( $result, $rows, $rv ) = Rogalik::DB->execute( 'select id from theCharacter where dead is null order by updated desc' );
#    say "найдено $rows живых персонажей";
    return unless $rows;

    my @ids;

    # 2. Collect ids of alive
    foreach my $line( @$result ) {
        push @ids, $line->{id};
    }

    # 3. Return ids
    return @ids;
}

sub main {
   my $app = Qt::Application( \@ARGV );

   my $shareDir = File::Spec->catdir(
       Rogalik::Config::BASEDIR,
       'share',
   );
   # TODO use File::ShareDir::dist_dir if CPAN distribution

   my $splashImagePath = File::Spec->catdir(
       $shareDir,
       'splash/splash.png'
   );
#   say $splashImagePath;

   my $splashPixmap = Qt::Pixmap( $splashImagePath );

   my $splash = Qt::SplashScreen( $splashPixmap );
   $splash->show();
   $splash->showMessage( '' );

   my @characterIds = init();

   sleep 2;

   my $mainWindow = MainWindow( @characterIds );
   $mainWindow->show();

   $splash->finish( $mainWindow );

   exit $app->exec();
}

main();
