#!/usr/bin/perl

use strict;
use warnings;

use 5.010;
use FindBin;
use File::Spec ();

use lib File::Spec->catdir( $FindBin::Bin, '../../lib' );
use Rogalik::DB;

# race
my ( $rc, $rv, $sql ) = Rogalik::DB->execute (
    "create table if not exists race (
        id           INTEGER,
        guiId        INTEGER,
        name         TEXT,
        strenght     INTEGER,
        dexterity    INTEGER,
        intelligence INTEGER,
        constitution INTEGER,
        wisdom       INTEGER,
        charisma     INTEGER,
        hit          INTEGER,
        shoot        INTEGER,
        throw        INTEGER,
        hitDie       INTEGER,
        XPmod        INTEGER,
        disarm       INTEGER,
        devices      INTEGER,
        save         INTEGER,
        stealth      INTEGER,
        infravision  INTEGER,
        diggig       INTEGER,
        search       TEXT,
        sustains     TEXT,
        resists      TEXT,
        extra        TEXT,
        primary key( id asc ) )"
);
